[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "fastapi-project"
version = "0.1.0"
description = "FastAPI MLOps Project"

[tool.setuptools.packages.find]
where = ["."]
include = ["src*"]

[tool.pyright]
include = ["src"]
extraPaths = ["."]
